### ISSUE TITLE
reply is disabled when all messages are un-decrypted

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#68] opened 2015-02-25 21:34 UTC
Version 1.8.1:
- Alice sling keys with a new user Bob that we have never imported before.
- Key import is successful.
- Alice receives a message from Bob.
- Alice has not sent any messages to Bob.
- Alice's List of threads shows Bob is 1/2 transparent (should be normal).
- Conversation detail view for Bob, shows the reply text box is missing (should be available).
- The message for Bob can be decrypted successfully.
- Bad Workaround: In order to enable reply in the same thread on the messages tab a user has to exit conversation list, select compose tab, select Bobs name from recipient list, type at least one message, press send, click on the messages tab, click on Bobs name in the thread list, now the reply text box is available.

**Comment by brnunes** [comment] 2015-03-13 23:53
Hi @mwfarb, I could not reproduce that.
When that happened, was it the first time that these devices exchanged keys?
The only way I think that this could happen is in the following scenario:

- Bob creates key KB1
- Bob creates key KB2
- Bob exchanges key KB2 with Alice
- Bob exchanges key KB1 with Alice

In this case, after receiving the key KB1, Alice will send the confirmation message but will not be able to send messages to Bob using KB1 because KB2 has the same push token and the same device and was created at a later date (se we consider it inactive - Issue #48).
It might be the case that this problem was already fixed while solving some of the other issues for version 1.8.2.
We can try to reproduce this issue in the version 1.8.2 next week.

**Comment by mwfarb** [comment] 2015-05-08 19:31
@brnunes This is still a confirmed issue in the latest code base, but its harder to create. The test scenario is a bit different, and simple really now that I now more about the root cause:
- In any conversation list, make sure that the only messages in the list are "Tap to decrypt", no other decrypted received messages and no other sent messages (delete all but the encrypted messages).
- Unable to compose a message.
- Workaround: tap to decrypt a message, or send a message with the "+" icon, now the reply compose edit box is available.
- The current state is much more usable, but we really should allow users to send message in this state.

I'd keep it open to make sure we show the compose window appropriately even for this case, but it's not something to focus on now, not necessary for 1.8.2. I'll keep it open but remove the milestone dependency. #76 is still highest priority.

**Comment by tenmalin** [comment] 2015-11-08 08:04
After testing, the issue has been resolved since exchanged parties will send confirm messages after key importing. Close the issue.

**Closed by tenmalin** 2015-11-08 08:04 UTC
Labels: bug
